// <auto-generated />
using System;
using Farmelo.Data.Write.EFContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Farmelo.Data.Migrations
{
    [DbContext(typeof(FarmeloDbContext))]
    [Migration("20260512075027_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Farmelo.Data.Write.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccentColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("INR");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBestseller")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Nutrition")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccentColor = "#0d6042",
                            BackgroundColor = "#eef6e4",
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "INR",
                            CurrentPrice = 249m,
                            Description = "Clean roasted crunch for daily snacking.",
                            Ingredients = "Roasted makhana, olive oil, rock salt.",
                            IsActive = true,
                            IsBestseller = true,
                            Name = "Plain Makhana",
                            Nutrition = "High protein, gluten-free, light roasted snack.",
                            Slug = "plain",
                            Weight = "200g"
                        },
                        new
                        {
                            Id = 2,
                            AccentColor = "#b83224",
                            BackgroundColor = "#fff3ec",
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "INR",
                            CurrentPrice = 269m,
                            Description = "Fiery chilli, garlic and tang.",
                            Ingredients = "Roasted makhana, olive oil, peri peri seasoning.",
                            IsActive = true,
                            IsBestseller = true,
                            Name = "Peri Peri",
                            Nutrition = "Roasted not fried, no palm oil, no added preservatives.",
                            Slug = "peri-peri",
                            Weight = "200g"
                        },
                        new
                        {
                            Id = 3,
                            AccentColor = "#25231d",
                            BackgroundColor = "#f4ede0",
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "INR",
                            CurrentPrice = 269m,
                            Description = "Classic seasoning with a sharp pepper finish.",
                            Ingredients = "Roasted makhana, olive oil, salt and pepper seasoning.",
                            IsActive = true,
                            IsBestseller = false,
                            Name = "Salt and Pepper",
                            Nutrition = "Roasted not fried, no palm oil, no added preservatives.",
                            Slug = "salt-and-pepper",
                            Weight = "200g"
                        },
                        new
                        {
                            Id = 4,
                            AccentColor = "#326f2b",
                            BackgroundColor = "#edf6dc",
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "INR",
                            CurrentPrice = 269m,
                            Description = "Smooth onion with herby creaminess.",
                            Ingredients = "Roasted makhana, olive oil, cream and onion seasoning.",
                            IsActive = true,
                            IsBestseller = true,
                            Name = "Cream and Onion",
                            Nutrition = "Roasted not fried, no palm oil, no added preservatives.",
                            Slug = "cream-and-onion",
                            Weight = "200g"
                        },
                        new
                        {
                            Id = 5,
                            AccentColor = "#d99622",
                            BackgroundColor = "#fff5d7",
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "INR",
                            CurrentPrice = 269m,
                            Description = "Creamy, savoury and snackable.",
                            Ingredients = "Roasted makhana, olive oil, cheesy delight seasoning.",
                            IsActive = true,
                            IsBestseller = true,
                            Name = "Cheesy Delight",
                            Nutrition = "Roasted not fried, no palm oil, no added preservatives.",
                            Slug = "cheesy-delight",
                            Weight = "200g"
                        });
                });

            modelBuilder.Entity("Farmelo.Data.Write.Entities.ProductPriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NewPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("OldPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPriceHistories", (string)null);
                });

            modelBuilder.Entity("Farmelo.Data.Write.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserAccounts", (string)null);
                });

            modelBuilder.Entity("Farmelo.Data.Write.Entities.ProductPriceHistory", b =>
                {
                    b.HasOne("Farmelo.Data.Write.Entities.UserAccount", "ChangedByUser")
                        .WithMany("PriceChanges")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Farmelo.Data.Write.Entities.Product", "Product")
                        .WithMany("PriceHistories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Farmelo.Data.Write.Entities.Product", b =>
                {
                    b.Navigation("PriceHistories");
                });

            modelBuilder.Entity("Farmelo.Data.Write.Entities.UserAccount", b =>
                {
                    b.Navigation("PriceChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
